version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: tomato
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: >
      sh -c "sleep 5
         python manage.py migrate && python manage.py sedddata &&
         sleep 2 &&
         python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db

