# Generated by Django 4.2.7 on 2023-11-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomatoai', '0003_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='tomatoai.ingredient'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='recipes',
            field=models.ManyToManyField(blank=True, related_name='restaurants', to='tomatoai.recipe'),
        ),
    ]
